In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
#from sklearn.neural_network import MLPRegressor
from math import sqrt

### Reading the data

In [7]:
data = pd.read_csv('winequality-red.csv')

In [8]:
data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [9]:
data.shape

(1599, 12)

### Selecting the input and output features for regression tasks

In [10]:
features = ['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides',
            'free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']

In [11]:
target = ['quality']

#### Checking for any null values in the dataset

In [12]:
data.isnull().any()

fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
dtype: bool

In [13]:
X = data[features]
y = data[target]

### Perform train test split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=200)

In [45]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
y_prediction = regressor.predict(X_test)
print(y_prediction[:5])
print('*'*40)
print(y_test[:5])

[[5.6362557 ]
 [5.73580131]
 [5.51754284]
 [5.48101339]
 [5.69866009]]
****************************************
      quality
366         7
1325        6
133         6
1418        5
1258        6


In [17]:
y_test.describe()

quality
count  528.000000
mean     5.575758
std      0.753196
min      3.000000
25%      5.000000
50%      5.500000
75%      6.000000
max      8.000000

In [18]:
RMSE = sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
print(RMSE)

0.6053813640476213


In [19]:
regressor = DecisionTreeRegressor(max_depth=50)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=50,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [20]:
y_prediction = regressor.predict(X_test)
y_prediction[:5]

array([7., 6., 5., 6., 6.])

In [21]:
y_test[:5]

quality
366         7
1325        6
133         6
1418        5
1258        6

In [22]:
RMSE = sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))

In [23]:
print(RMSE)

0.7869677133263993


When comparing two or more regression models, then the model with small `RMSE` will be better.

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
data_classifier = data.copy()

In [26]:
data_classifier.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [27]:
data_classifier['quality'].dtype

dtype('int64')

Next we shall create a new column called Quality Label. This column will contain the values of 0 & 1

1 <- good,
0 <- bad

In [28]:
data_classifier['quality_label'] = (data_classifier['quality'] > 6.5)*1

In [29]:
data_classifier['quality_label']

0       0
1       0
2       0
3       0
4       0
       ..
1594    0
1595    0
1596    0
1597    0
1598    0
Name: quality_label, Length: 1599, dtype: int64

In [30]:
features = ['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides',
            'free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']
target_classifier = ['quality_label']

In [31]:
X = data_classifier[features]
y = data_classifier[target_classifier]

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=324)

In [33]:
wine_quality_classifier = DecisionTreeClassifier(max_leaf_nodes=20, random_state=0)

In [34]:
wine_quality_classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=20,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [35]:
prediction = wine_quality_classifier.predict(X_test)
print(prediction[:5])
print('*'*10)
print(y_test['quality_label'][:5])

[0 0 0 1 0]
**********
1144    0
1532    0
618     0
205     1
1384    0
Name: quality_label, dtype: int64


In [36]:
accuracy_score(y_true=y_test, y_pred=prediction)

0.9034090909090909

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
data_classifier.head()

fixed acidity  volatile acidity  ...  quality  quality_label
0            7.4              0.70  ...        5              0
1            7.8              0.88  ...        5              0
2            7.8              0.76  ...        5              0
3           11.2              0.28  ...        6              0
4            7.4              0.70  ...        5              0

[5 rows x 13 columns]

In [39]:
features = ['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides',
            'free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']
target_classifier = ['quality_label']

In [40]:
X = data_classifier[features]
y = data_classifier[target_classifier]

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=324)

In [42]:
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [43]:
prediction = logistic_regression.predict(X_test)
print(prediction[:5])
print(y_test[:5])

[0 0 0 0 0]
      quality_label
1144              0
1532              0
618               0
205               1
1384              0


In [44]:
accuracy_score(y_true=y_test, y_pred=prediction)

0.884469696969697